import { Job, Application, HRProfile } from '@/types';

export const MOCK_HR_PROFILES: HRProfile[] = [
    { id: 'hr-1', name: 'Alice Johnson', role: 'Admin', avatarUrl: 'https://i.pravatar.cc/150?u=hr-1' },
    { id: 'hr-2', name: 'Bob Smith', role: 'Recruiter', avatarUrl: 'https://i.pravatar.cc/150?u=hr-2' },
    { id: 'hr-3', name: 'Charlie Davis', role: 'Recruiter', avatarUrl: 'https://i.pravatar.cc/150?u=hr-3' },
];

export const MOCK_JOBS: Job[] = [
    {
        id: 'job-1',
        title: 'Senior Frontend Engineer',
        description: '<p>We are looking for an experienced Frontend Engineer to join our team...</p>',
        location: 'New York, NY',
        locationType: 'Hybrid',
        type: 'Full-time',
        salaryRange: '$120k - $160k',
        questions: ['Years of experience with React?', 'Link to portfolio?'],
        status: 'Published',
        createdAt: '2023-10-01T10:00:00Z',
        applicantsCount: 12,
    },
    {
        id: 'job-2',
        title: 'Product Designer',
        description: '<p>Join our design team to create amazing user experiences...</p>',
        location: 'San Francisco, CA',
        locationType: 'Office',
        type: 'Full-time',
        salaryRange: '$100k - $140k',
        questions: ['Link to Dribbble/Behance?'],
        status: 'Published',
        createdAt: '2023-10-05T14:30:00Z',
        applicantsCount: 8,
    },
    {
        id: 'job-3',
        title: 'Marketing Intern',
        description: '<p>Great opportunity for students...</p>',
        location: 'Remote',
        locationType: 'Remote',
        type: 'Internship',
        salaryRange: '$20/hr',
        questions: ['Available start date?'],
        status: 'Draft',
        createdAt: '2023-10-10T09:00:00Z',
        applicantsCount: 0,
    },
];

export const MOCK_APPLICATIONS: Application[] = [
    {
        id: 'app-1',
        jobId: 'job-1',
        applicantId: 'applicant-1',
        applicant: {
            id: 'applicant-1',
            name: 'John Doe',
            email: 'john@example.com',
            phone: '+1 555-0101',
            avatarUrl: 'https://i.pravatar.cc/150?u=applicant-1',
            resumeUrl: '#',
        },
        status: 'New',
        appliedAt: '2023-10-12T08:00:00Z',
        comments: [],
    },
    {
        id: 'app-2',
        jobId: 'job-1',
        applicantId: 'applicant-2',
        applicant: {
            id: 'applicant-2',
            name: 'Jane Smith',
            email: 'jane@example.com',
            phone: '+1 555-0102',
            avatarUrl: 'https://i.pravatar.cc/150?u=applicant-2',
            resumeUrl: '#',
        },
        status: 'Screening',
        appliedAt: '2023-10-12T09:15:00Z',
        assignedTo: 'hr-2',
        score: 85,
        comments: [
            {
                id: 'c-1',
                authorId: 'hr-2',
                authorName: 'Bob Smith',
                content: 'Looks promising, good React experience.',
                createdAt: '2023-10-12T10:00:00Z',
            },
        ],
    },
    {
        id: 'app-3',
        jobId: 'job-2',
        applicantId: 'applicant-3',
        applicant: {
            id: 'applicant-3',
            name: 'Mike Brown',
            email: 'mike@example.com',
            phone: '+1 555-0103',
            avatarUrl: 'https://i.pravatar.cc/150?u=applicant-3',
            resumeUrl: '#',
        },
        status: 'Interview',
        appliedAt: '2023-10-13T11:00:00Z',
        assignedTo: 'hr-1',
        comments: [],
    },
    {
        id: 'app-4',
        jobId: 'job-1',
        applicantId: 'applicant-4',
        applicant: {
            id: 'applicant-4',
            name: 'Sarah Wilson',
            email: 'sarah@example.com',
            phone: '+1 555-0104',
            avatarUrl: 'https://i.pravatar.cc/150?u=applicant-4',
            resumeUrl: '#',
        },
        status: 'Rejected',
        appliedAt: '2023-10-11T16:45:00Z',
        assignedTo: 'hr-3',
        notes: 'Not enough experience with TypeScript.',
        comments: [],
    },
];
